import { writeFileSync } from "fs"
import type { AuditResult, Report } from "../types.ts"

function formatAuditTableMarkdown(report: Report): string[] {
  const lines: string[] = []

  if (report.audit && report.postAudit) {
    lines.push("## Before / After")
    lines.push("")
    lines.push("| Check | Before | After |")
    lines.push("|-------|--------|-------|")
    for (const [i, before] of report.audit.checks.entries()) {
      const after = report.postAudit.checks[i]
      const afterStatus = after?.status ?? "—"
      const changed = before.status !== afterStatus ? " **changed**" : ""
      lines.push(`| ${before.name} | ${before.status} | ${afterStatus}${changed} |`)
    }
    lines.push("")
  } else if (report.audit) {
    lines.push("## Pre-Hardening Audit")
    lines.push("")
    lines.push("| Check | Status |")
    lines.push("|-------|--------|")
    for (const check of report.audit.checks) {
      lines.push(`| ${check.name} | ${check.status} |`)
    }
    lines.push("")
  }

  return lines
}

export function exportReportMarkdown(report: Report): string {
  const sanitizedIp = report.serverIp.replace(/:/g, "-")
  const filename = `securbuntu-report-${sanitizedIp}-${report.date}.md`

  const lines: string[] = []
  lines.push("# SecurBuntu Hardening Report")
  lines.push("")
  lines.push("| Field | Value |")
  lines.push("|-------|-------|")
  lines.push(`| Server | ${report.serverIp} |`)
  lines.push(`| User | ${report.connectionUser} |`)
  if (report.sudoUser) {
    lines.push(`| New Sudo User | ${report.sudoUser} |`)
  }
  lines.push(`| Ubuntu | ${report.ubuntuVersion} |`)
  lines.push(`| Date | ${report.date} |`)
  if (report.newSshPort) {
    lines.push(`| New SSH Port | ${report.newSshPort} |`)
  }
  lines.push("")
  lines.push("## Tasks")
  lines.push("")

  for (const result of report.results) {
    const icon = result.success ? "+" : "-"
    lines.push(`### ${icon} ${result.name}`)
    lines.push("")
    lines.push(result.message)
    if (result.details) {
      lines.push("")
      lines.push(`> ${result.details}`)
    }
    lines.push("")
  }

  lines.push(...formatAuditTableMarkdown(report))

  if (report.newSshPort) {
    lines.push("## Important")
    lines.push("")
    const user = report.sudoUser ?? report.connectionUser
    lines.push("SSH port has been changed. Use this command to connect:")
    lines.push("")
    lines.push("```bash")
    lines.push(`ssh -p ${report.newSshPort} ${user}@${report.serverIp}`)
    lines.push("```")
    lines.push("")
  }

  lines.push("---")
  lines.push("*Generated by SecurBuntu*")

  const content = lines.join("\n")
  writeFileSync(filename, content, "utf-8")
  return filename
}

export function exportAuditMarkdown(audit: AuditResult, serverIp: string, date: string): string {
  const sanitizedIp = serverIp.replace(/:/g, "-")
  const filename = `securbuntu-audit-${sanitizedIp}-${date}.md`

  const lines: string[] = []
  lines.push("# SecurBuntu Security Audit")
  lines.push("")
  lines.push("| Field | Value |")
  lines.push("|-------|-------|")
  lines.push(`| Server | ${serverIp} |`)
  lines.push(`| Date | ${date} |`)
  lines.push("")
  lines.push("## Checks")
  lines.push("")
  lines.push("| Check | Status |")
  lines.push("|-------|--------|")
  for (const check of audit.checks) {
    lines.push(`| ${check.name} | ${check.status} |`)
  }
  lines.push("")
  lines.push("---")
  lines.push("*Generated by SecurBuntu*")

  const content = lines.join("\n")
  writeFileSync(filename, content, "utf-8")
  return filename
}
