import { afterEach, describe, expect, test } from "bun:test"
import { readFileSync, unlinkSync } from "fs"
import { exportAuditMarkdown, exportReportMarkdown } from "../report.js"
import type { AuditResult, Report } from "../types.js"

const cleanupFiles: string[] = []

afterEach(() => {
  for (const f of cleanupFiles) {
    try {
      unlinkSync(f)
    } catch {
      /* ignored */
    }
  }
  cleanupFiles.length = 0
})

function makeReport(overrides: Partial<Report> = {}): Report {
  return {
    serverIp: "192.168.1.100",
    connectionUser: "root",
    date: "2026-03-15",
    ubuntuVersion: "24.04",
    results: [
      { name: "System Update", success: true, message: "System packages updated" },
      {
        name: "UFW Firewall",
        success: true,
        message: "UFW installed and configured",
        details: "Allowed: 22/tcp, 80/tcp",
      },
    ],
    ...overrides,
  }
}

describe("exportReportMarkdown", () => {
  test("generates correct filename", () => {
    const filename = exportReportMarkdown(makeReport())
    cleanupFiles.push(filename)
    expect(filename).toBe("securbuntu-report-192.168.1.100-2026-03-15.md")
  })

  test("sanitizes IPv6 colons in filename", () => {
    const filename = exportReportMarkdown(makeReport({ serverIp: "::1" }))
    cleanupFiles.push(filename)
    expect(filename).toBe("securbuntu-report---1-2026-03-15.md")
  })

  test("includes server metadata", () => {
    const filename = exportReportMarkdown(makeReport())
    cleanupFiles.push(filename)
    const content = readFileSync(filename, "utf-8")
    expect(content).toContain("# SecurBuntu Hardening Report")
    expect(content).toContain("| Server | 192.168.1.100 |")
    expect(content).toContain("| User | root |")
    expect(content).toContain("| Ubuntu | 24.04 |")
  })

  test("includes sudo user when present", () => {
    const filename = exportReportMarkdown(makeReport({ sudoUser: "deploy" }))
    cleanupFiles.push(filename)
    const content = readFileSync(filename, "utf-8")
    expect(content).toContain("| New Sudo User | deploy |")
  })

  test("omits sudo user when absent", () => {
    const filename = exportReportMarkdown(makeReport())
    cleanupFiles.push(filename)
    const content = readFileSync(filename, "utf-8")
    expect(content).not.toContain("New Sudo User")
  })

  test("includes task results with icons", () => {
    const filename = exportReportMarkdown(makeReport())
    cleanupFiles.push(filename)
    const content = readFileSync(filename, "utf-8")
    expect(content).toContain("### + System Update")
    expect(content).toContain("### + UFW Firewall")
  })

  test("includes failed task with minus icon", () => {
    const filename = exportReportMarkdown(
      makeReport({
        results: [{ name: "Test", success: false, message: "Failed" }],
      }),
    )
    cleanupFiles.push(filename)
    const content = readFileSync(filename, "utf-8")
    expect(content).toContain("### - Test")
  })

  test("includes task details as blockquote", () => {
    const filename = exportReportMarkdown(makeReport())
    cleanupFiles.push(filename)
    const content = readFileSync(filename, "utf-8")
    expect(content).toContain("> Allowed: 22/tcp, 80/tcp")
  })

  test("includes SSH port warning when changed", () => {
    const filename = exportReportMarkdown(makeReport({ newSshPort: 2222 }))
    cleanupFiles.push(filename)
    const content = readFileSync(filename, "utf-8")
    expect(content).toContain("## Important")
    expect(content).toContain("ssh -p 2222 root@192.168.1.100")
  })

  test("SSH port warning uses sudo user when available", () => {
    const filename = exportReportMarkdown(makeReport({ newSshPort: 2222, sudoUser: "deploy" }))
    cleanupFiles.push(filename)
    const content = readFileSync(filename, "utf-8")
    expect(content).toContain("ssh -p 2222 deploy@192.168.1.100")
  })

  test("includes audit section when present", () => {
    const audit: AuditResult = {
      checks: [
        { name: "SSH Port", status: "22 (default)" },
        { name: "UFW Firewall", status: "active" },
      ],
    }
    const filename = exportReportMarkdown(makeReport({ audit }))
    cleanupFiles.push(filename)
    const content = readFileSync(filename, "utf-8")
    expect(content).toContain("## Pre-Hardening Audit")
    expect(content).toContain("| SSH Port | 22 (default) |")
    expect(content).toContain("| UFW Firewall | active |")
  })

  test("includes footer", () => {
    const filename = exportReportMarkdown(makeReport())
    cleanupFiles.push(filename)
    const content = readFileSync(filename, "utf-8")
    expect(content).toContain("*Generated by SecurBuntu*")
  })
})

describe("exportAuditMarkdown", () => {
  test("generates correct filename", () => {
    const audit: AuditResult = { checks: [{ name: "Test", status: "ok" }] }
    const filename = exportAuditMarkdown(audit, "10.0.0.1", "2026-03-15")
    cleanupFiles.push(filename)
    expect(filename).toBe("securbuntu-audit-10.0.0.1-2026-03-15.md")
  })

  test("includes audit checks table", () => {
    const audit: AuditResult = {
      checks: [
        { name: "Fail2ban", status: "active" },
        { name: "Sysctl", status: "default" },
      ],
    }
    const filename = exportAuditMarkdown(audit, "10.0.0.1", "2026-03-15")
    cleanupFiles.push(filename)
    const content = readFileSync(filename, "utf-8")
    expect(content).toContain("# SecurBuntu Security Audit")
    expect(content).toContain("| Server | 10.0.0.1 |")
    expect(content).toContain("| Fail2ban | active |")
    expect(content).toContain("| Sysctl | default |")
  })
})
