import pc from "picocolors"
import { note } from "@clack/prompts"
import { writeFileSync } from "fs"
import type { Report, AuditResult } from "./types.js"

export function displayReport(report: Report): void {
  const lines: string[] = []

  lines.push(`${pc.bold("Server:")} ${report.serverIp}`)
  lines.push(`${pc.bold("User:")} ${report.connectionUser}`)
  if (report.sudoUser) {
    lines.push(`${pc.bold("New sudo user:")} ${pc.cyan(report.sudoUser)}`)
  }
  lines.push(`${pc.bold("Ubuntu:")} ${report.ubuntuVersion}`)
  lines.push(`${pc.bold("Date:")} ${report.date}`)
  lines.push("")

  for (const result of report.results) {
    const icon = result.success ? pc.green("✓") : pc.red("✗")
    lines.push(`${icon} ${pc.bold(result.name)}: ${result.message}`)
    if (result.details) {
      lines.push(`  ${pc.dim(result.details)}`)
    }
  }

  if (report.audit) {
    lines.push("")
    lines.push(pc.bold("Audit (pre-hardening):"))
    for (const check of report.audit.checks) {
      lines.push(`  ${pc.dim(check.name)}: ${check.status}`)
    }
  }

  if (report.newSshPort) {
    lines.push("")
    lines.push(pc.yellow(pc.bold(`⚠  SSH port changed to ${report.newSshPort}`)))
    const user = report.sudoUser ?? report.connectionUser
    lines.push(pc.cyan(`   ssh -p ${report.newSshPort} ${user}@${report.serverIp}`))
  }

  note(lines.join("\n"), "SecurBuntu Report")
}

export function exportReportMarkdown(report: Report): string {
  const sanitizedIp = report.serverIp.replace(/:/g, "-")
  const filename = `securbuntu-report-${sanitizedIp}-${report.date}.md`

  const lines: string[] = []
  lines.push("# SecurBuntu Hardening Report")
  lines.push("")
  lines.push("| Field | Value |")
  lines.push("|-------|-------|")
  lines.push(`| Server | ${report.serverIp} |`)
  lines.push(`| User | ${report.connectionUser} |`)
  if (report.sudoUser) {
    lines.push(`| New Sudo User | ${report.sudoUser} |`)
  }
  lines.push(`| Ubuntu | ${report.ubuntuVersion} |`)
  lines.push(`| Date | ${report.date} |`)
  if (report.newSshPort) {
    lines.push(`| New SSH Port | ${report.newSshPort} |`)
  }
  lines.push("")
  lines.push("## Tasks")
  lines.push("")

  for (const result of report.results) {
    const icon = result.success ? "+" : "-"
    lines.push(`### ${icon} ${result.name}`)
    lines.push("")
    lines.push(result.message)
    if (result.details) {
      lines.push("")
      lines.push(`> ${result.details}`)
    }
    lines.push("")
  }

  if (report.audit) {
    lines.push("## Pre-Hardening Audit")
    lines.push("")
    lines.push("| Check | Status |")
    lines.push("|-------|--------|")
    for (const check of report.audit.checks) {
      lines.push(`| ${check.name} | ${check.status} |`)
    }
    lines.push("")
  }

  if (report.newSshPort) {
    lines.push("## Important")
    lines.push("")
    const user = report.sudoUser ?? report.connectionUser
    lines.push("SSH port has been changed. Use this command to connect:")
    lines.push("")
    lines.push("```bash")
    lines.push(`ssh -p ${report.newSshPort} ${user}@${report.serverIp}`)
    lines.push("```")
    lines.push("")
  }

  lines.push("---")
  lines.push("*Generated by SecurBuntu*")

  const content = lines.join("\n")
  writeFileSync(filename, content, "utf-8")
  return filename
}

export function exportAuditMarkdown(audit: AuditResult, serverIp: string, date: string): string {
  const sanitizedIp = serverIp.replace(/:/g, "-")
  const filename = `securbuntu-audit-${sanitizedIp}-${date}.md`

  const lines: string[] = []
  lines.push("# SecurBuntu Security Audit")
  lines.push("")
  lines.push(`| Field | Value |`)
  lines.push(`|-------|-------|`)
  lines.push(`| Server | ${serverIp} |`)
  lines.push(`| Date | ${date} |`)
  lines.push("")
  lines.push("## Checks")
  lines.push("")
  lines.push("| Check | Status |")
  lines.push("|-------|--------|")
  for (const check of audit.checks) {
    lines.push(`| ${check.name} | ${check.status} |`)
  }
  lines.push("")
  lines.push("---")
  lines.push("*Generated by SecurBuntu*")

  const content = lines.join("\n")
  writeFileSync(filename, content, "utf-8")
  return filename
}
